# Form implementation generated from reading ui file 'license_select.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LicenseSelectForm(object):
    def setupUi(self, LicenseSelectForm):
        LicenseSelectForm.setObjectName("LicenseSelectForm")
        LicenseSelectForm.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        LicenseSelectForm.resize(380, 150)
        LicenseSelectForm.setMinimumSize(QtCore.QSize(380, 150))
        LicenseSelectForm.setMaximumSize(QtCore.QSize(380, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        LicenseSelectForm.setFont(font)
        self.label_2 = QtWidgets.QLabel(LicenseSelectForm)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 361, 41))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(LicenseSelectForm)
        self.widget.setGeometry(QtCore.QRect(9, 60, 361, 41))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.widget)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(LicenseSelectForm)
        self.widget1.setGeometry(QtCore.QRect(210, 110, 161, 27))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_conform = QtWidgets.QPushButton(self.widget1)
        self.pushButton_conform.setObjectName("pushButton_conform")
        self.gridLayout_2.addWidget(self.pushButton_conform, 0, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget1)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_2.addWidget(self.pushButton_cancel, 0, 1, 1, 1)

        self.retranslateUi(LicenseSelectForm)
        QtCore.QMetaObject.connectSlotsByName(LicenseSelectForm)

    def retranslateUi(self, LicenseSelectForm):
        _translate = QtCore.QCoreApplication.translate
        LicenseSelectForm.setWindowTitle(_translate("LicenseSelectForm", "Form"))
        self.label_2.setText(_translate("LicenseSelectForm", "当前程序路径下未找到License文件，为避免程序启动失败，\n"
"请指定License文件路径。"))
        self.label.setText(_translate("LicenseSelectForm", "License文件路径："))
        self.toolButton.setText(_translate("LicenseSelectForm", "..."))
        self.pushButton_conform.setText(_translate("LicenseSelectForm", "确定"))
        self.pushButton_cancel.setText(_translate("LicenseSelectForm", "取消"))
