# Form implementation generated from reading ui file 'root_login.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RootLoginForm(object):
    def setupUi(self, RootLoginForm):
        RootLoginForm.setObjectName("RootLoginForm")
        RootLoginForm.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        RootLoginForm.resize(200, 170)
        RootLoginForm.setMinimumSize(QtCore.QSize(200, 170))
        RootLoginForm.setMaximumSize(QtCore.QSize(200, 170))
        self.label_root = QtWidgets.QLabel(RootLoginForm)
        self.label_root.setGeometry(QtCore.QRect(9, 48, 48, 16))
        self.label_root.setObjectName("label_root")
        self.label_password = QtWidgets.QLabel(RootLoginForm)
        self.label_password.setGeometry(QtCore.QRect(9, 93, 36, 16))
        self.label_password.setObjectName("label_password")
        self.lineEdit_root = QtWidgets.QLineEdit(RootLoginForm)
        self.lineEdit_root.setGeometry(QtCore.QRect(63, 48, 128, 21))
        self.lineEdit_root.setObjectName("lineEdit_root")
        self.lineEdit_password = QtWidgets.QLineEdit(RootLoginForm)
        self.lineEdit_password.setGeometry(QtCore.QRect(63, 93, 128, 21))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label = QtWidgets.QLabel(RootLoginForm)
        self.label.setGeometry(QtCore.QRect(9, 9, 141, 16))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(RootLoginForm)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 130, 158, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_conform = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_conform.setObjectName("pushButton_conform")
        self.gridLayout.addWidget(self.pushButton_conform, 0, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 0, 1, 1, 1)

        self.retranslateUi(RootLoginForm)
        QtCore.QMetaObject.connectSlotsByName(RootLoginForm)

    def retranslateUi(self, RootLoginForm):
        _translate = QtCore.QCoreApplication.translate
        RootLoginForm.setWindowTitle(_translate("RootLoginForm", "登录"))
        self.label_root.setText(_translate("RootLoginForm", "账号："))
        self.label_password.setText(_translate("RootLoginForm", "密码："))
        self.lineEdit_root.setText(_translate("RootLoginForm", "root"))
        self.label.setText(_translate("RootLoginForm", "请使用已有账号登录："))
        self.pushButton_conform.setText(_translate("RootLoginForm", "确定"))
        self.pushButton_cancel.setText(_translate("RootLoginForm", "取消"))
