# Form implementation generated from reading ui file 'save_db_config.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SaveDbConfigForm(object):
    def setupUi(self, SaveDbConfigForm):
        SaveDbConfigForm.setObjectName("SaveDbConfigForm")
        SaveDbConfigForm.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        SaveDbConfigForm.resize(250, 72)
        SaveDbConfigForm.setMinimumSize(QtCore.QSize(250, 72))
        SaveDbConfigForm.setMaximumSize(QtCore.QSize(250, 72))
        font = QtGui.QFont()
        font.setPointSize(10)
        SaveDbConfigForm.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(SaveDbConfigForm)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_config_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_config_name.setObjectName("label_config_name")
        self.gridLayout.addWidget(self.label_config_name, 0, 0, 1, 1)
        self.lineEdit_config_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_config_name.setObjectName("lineEdit_config_name")
        self.gridLayout.addWidget(self.lineEdit_config_name, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(SaveDbConfigForm)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 40, 158, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_conform = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_conform.setObjectName("pushButton_conform")
        self.horizontalLayout.addWidget(self.pushButton_conform)
        self.pushButton_cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)

        self.retranslateUi(SaveDbConfigForm)
        QtCore.QMetaObject.connectSlotsByName(SaveDbConfigForm)

    def retranslateUi(self, SaveDbConfigForm):
        _translate = QtCore.QCoreApplication.translate
        SaveDbConfigForm.setWindowTitle(_translate("SaveDbConfigForm", "保存配置"))
        self.label_config_name.setText(_translate("SaveDbConfigForm", "配置名称："))
        self.pushButton_conform.setText(_translate("SaveDbConfigForm", "确定"))
        self.pushButton_cancel.setText(_translate("SaveDbConfigForm", "取消"))
